### ISSUE TITLE
example_07_jpeg.v  figure not displayed when w larger than h

### ISSUE THREAD

**Issue by sevehub** [vlang/pdf#14]
Seems that when V divides two integers doesn't promote the result to float.
In the code below h_scale will be set to zero if w is larger than h.	
<pre><code>
// Line 48 example_07_jpeg.v 
// get width and height in pixel of the jpeg image
_, w, h := pdf.get_jpeg_info(jpeg_data)
h_scale := h / w
</code></pre>
I suggest:
h_scale := f32(h)/f32(w)

Do you prefer a PR?

**Comment by JalonSolov** [comment]
Integer division never promotes to float.  Not in any language I've used, anyway.

I think your change is a good idea, though it will need to be tested to make sure that changing `h_scale` to a float doesn't adversely affect anything else.

If you would like to submit a PR, that would be great!

**Comment by sevehub** [comment]
Yes, C doesn't either while Python has specific operators for float (/) and floor division (//).
Wouldn't it be better if the function _get_jpeg_info_ returns the aspect ratio as well ?
<pre><code>
diff --git a/pdf.v b/pdf.v
index 34a2ec3..9783dcd 100644
--- a/pdf.v
+++ b/pdf.v
@@ -684,11 +684,11 @@ pub fn (mut p Pdf) get_base_font_id(font_name string) string {
 * JPEG resources
 *
 ******************************************************************************/
-// get_jpeg_info get the width,height and number of bit per pixel of a jpeg file
-pub fn get_jpeg_info(data []u8) (int, int, int) {
-	// cehck for empty
+// get_jpeg_info get the width,height, aspect ratio and number of bit per pixel of a jpeg file
+pub fn get_jpeg_info(data []u8) (int, int, int, f32) {
+	// check for empty
 	if data.len <= 0 {
-		return 0, 0, 0
+		return 0, 0, 0, 0.0
 	}
 
 	mut i := 0
@@ -704,16 +704,16 @@ pub fn get_jpeg_info(data []u8) (int, int, int) {
 			width := (u16(data[i]) << 8 | data[i + 1])
 			i += 2
 			// println("get jped params l: $length nbit: $n_bit w:[$width] h:[$height].")
-			return n_bit, width, height
+			return n_bit, width, height, f32(height)/f32(width)
 		}
 		i++
 	}
-	return 0, 0, 0
+	return 0, 0, 0, 0.0
 }
 
 // add_jpeg_resource add a jpeg as resource to the pdf
 pub fn (mut p Pdf) add_jpeg_resource(jpeg_data []u8) int {
-	jpg_n_bit, jpg_w, jpg_h := get_jpeg_info(jpeg_data)
+	jpg_n_bit, jpg_w, jpg_h, _ := get_jpeg_info(jpeg_data)
 	mut jpeg_obj := Obj{
 		id: p.get_new_id()
 		is_stream: true

</code></pre>

**Comment by penguindark** [comment]
It can be a good Idea, can you do a PR? :)
To be honest I  implemented only a base version of the JPEG get info function,
probably it must be evolved in order to manage more complex jpeg.

**Comment by sevehub** [comment]
Ok, meanwhile I close this issue.
