### ISSUE TITLE
compress true option fails

### ISSUE THREAD

**Issue by jojo05** [vlang/pdf#4]
Hi,
I can see someone has put a lot of care in developing this library. I just want to report that the examples which have the compress: true option fail. It returns -10000 error

Also, I want to generate a pdf with a table. Is there any ready-made or approximate solution I can use ?
Thanks

**Comment by penguindark** [comment]
Can you post here a snippet of the code that doesn't work?
Please write here your OS and V version that you are using :) tnx.

About the table support can be in future, first we need to add the true type font support.

**Comment by jojo05** [comment]
4.18.19-100.fc27.x86_64, V 0.1.29 62a692b

ERROR!: Compress Failed! error: -10000

The document is written ok when compress: false

------------------------------------------

import pdf
import os

fn main() {

        mut doc := pdf.Pdf{}

        doc.init()

        page_n := doc.create_page({
                format: 'A4',
                gen_content_obj: true,
                compress: true
        })

        mut page := &doc.page_list[page_n]
        page.user_unit = pdf.mm_unit

        mut fnt_params := pdf.Text_params{
                font_size    : 22.0
                font_name    : "Helvetica"
                s_color : {r:0,g:0,b:0}
                f_color : {r:0,g:0,b:0}
        }
        if !doc.use_base_font(fnt_params.font_name) {
                eprintln("ERROR: Font ${fnt_params.font_name} not available!")
                return
        }

        page.push_content( page.draw_base_text("Test string.", 10, 10, fnt_params))

        txt := doc.render()
        os.write_file_array('t.pdf', txt.buf)
}

**Comment by penguindark** [comment]
What is you OS? Windows, linux, macos?

**Comment by jojo05** [comment]
Linux Fedora Core 27

**Comment by penguindark** [comment]
I'll test it Monday, at the present time I'm using and Ubuntu. 
I'll let you know ASAP.

**Comment by penguindark** [comment]
I've checked it, there is a problem with the -prod flag with the included zip library.
I'll check it better as soon I'll have some spare time, for now please excuse me.

**Comment by jojo05** [comment]
It's not urgent at all. This happens without the -prod flag. Thank you

**Comment by JalonSolov** [comment]
Still failing today, with latest V, without `-prod` flag.
