### ISSUE TITLE
Strange output when using some commen symbols like €

### ISSUE THREAD

**Issue by BolverBlitz** [vlang/pdf#9]
Input string is "187,50 €" and v/PDF prints "187,50¬†‚Ç¨".

```v
mut fnt_params_list := pdf.Text_params{
  font_size: 14.0
  font_name: 'Helvetica'
  s_color: pdf.RGB{
    r: 0
    g: 0
    b: 0
    }
  f_color: pdf.RGB{
    r: 0
    g: 0
    b: 0
    }
}
fnt_params_list.text_align = .right
//item.price = 187,50 €
page.text_box(item.price, pdf.Box{
  x: 180
  y: y - 5
  w: 200 - 180
  h: 4
}, fnt_params_list)
```

**Comment by JalonSolov** [comment]
Complete test:  https://raw.githubusercontent.com/EBG-PW/LAN-Abrechnung/master/pdfGenerator/main.v

**Comment by BolverBlitz** [comment]
It will also panic wihout a logo.jpg
Lines: 135, 136, 139 and 166 - 168 need to be removed if its not present

The config required to run the my full code:
*Make sure its just 1 line json, not formated.
```js
[{"headline":"Sommerlan 2021 Invoice","userid":"206921999","username":"BolverBlitz","date":"21.9.2022","items":[{"artikel":"Item","amount":"Amount","price":"Price"},{"artikel":"Electricity (in kWh)","amount":"5,701x","price":"57,01 €"},{"artikel":"Fanta","amount":"5x","price":"4,95 €"},{"artikel":"Milka Alpenmilch","amount":"14x","price":"18,06 €"},{"artikel":"Paprika Chips","amount":"4x","price":"11,96 €"},{"artikel":"Sourcream Chips","amount":"2x","price":"7,98 €"},{"artikel":"Spende","amount":"2x","price":"187,50 €"},{"artikel":"Vanille Milch","amount":"2x","price":"3,98 €"},{"artikel":"Prepaid","amount":"","price":"187,50 €"},{"artikel":"Total spend","amount":"","price":"234,43 €"},{"artikel":"Difference","amount":"","price":"-46,93 €"}]}]
```

**Comment by penguindark** [comment]
Ok, tnx, I'll have a check on it tonight

**Comment by penguindark** [comment]
@BolverBlitz Can you tell me your OS and what font are using as default in your OS?

**Comment by BolverBlitz** [comment]
Windows 10/11 and Ubuntu 22.04 in WSL. All defaults, i can´t find the name, looking it up brings up "Segoe UI font"

**Comment by penguindark** [comment]
Tnx, found the issue, working on it, I let you know asap
Sorry for the delay but I'm very busy these days.

**Comment by penguindark** [comment]
@BolverBlitz you can have a look at new example 09 with Euro symbol.
You need to use an imported ttf font with the Euro symbol in it.
As I said on discord the default embedded fonts are "ancient" and does not normally support €.

**Comment by BolverBlitz** [comment]
Ok, great. Tryed the example and it works here aswell. Thank you

**Comment by penguindark** [comment]
I hope to simplify the procedure in future. :)
